<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>7af67e0b-d868-4633-a3ac-c2ec5a13e3a6</UserSecretsId>
    </PropertyGroup>

</Project>
